#!/bin/sh

set -eu

test -f /etc/ssh/keys/ssh_host_rsa_key || ssh-keygen -N "" -t rsa -f /etc/ssh/keys/ssh_host_rsa_key
test -f /etc/ssh/keys/ssh_host_dsa_key || ssh-keygen -N "" -t dsa -f /etc/ssh/keys/ssh_host_dsa_key
test -f /etc/ssh/keys/ssh_host_ecdsa_key || ssh-keygen -N "" -t ecdsa -f /etc/ssh/keys/ssh_host_ecdsa_key
test -f /etc/ssh/keys/ssh_host_ed25519_key || ssh-keygen -N "" -t ed25519 -f /etc/ssh/keys/ssh_host_ed25519_key

exec /usr/sbin/sshd -D
